#!/usr/bin/env zsh

emulate -LR zsh

#
# Main code
#

# Standard screen saver before-loop block
fpath+=( "${0%/*}" )
autoload morlib
morlib
-morlib_begin
trap "-morlib_end; exit" TERM INT QUIT
trap "-morlib_end" EXIT
# End of standard screen saver before-loop block

redraw_delay=300

# Main loop
# Does nothing, the -morlib_begin
# call already cleared the screen
while (( 1 )); do
    sleep $redraw_delay
done

# vim:ft=zsh
